[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

[dev]
  command = "npm run dev"
  targetPort = 5173
  port = 8888
  autoLaunch = true

[functions]
  # Directory for serverless functions
  directory = "netlify/functions"
  
[functions."*"]
  # 26 seconds timeout for Pro plan (maximum allowed)
  timeout = 26
  # Increase body size limit to 50MB (maximum allowed)
  body_size_limit = "50MB"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self' https:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https:; style-src 'self' 'unsafe-inline' https:; img-src 'self' data: https: blob:; connect-src 'self' https: wss:; frame-src https://phantom.app https://*.phantom.app; child-src https://phantom.app https://*.phantom.app;"

[[redirects]]
  from = "/vite.svg"
  to = "/favicon.ico"
  status = 200