
import { Link } from 'react-router-dom';

export function LegalPage() {
  return (
    <div className="flex flex-col h-screen bg-bg-main text-text-primary">
      {/* Header */}
      <header className="flex items-center justify-between px-4 py-3 border-b border-border">
        <div className="flex items-center gap-3">
          <Link 
            to="/"
            className="flex items-center gap-3 hover:opacity-80 transition-opacity px-2 py-1 rounded-lg"
          >
            <img 
              src="/GoonGPT-notext.png" 
              alt="GoonGPT Logo" 
              className="h-14 w-auto"
            />
          </Link>
        </div>
        
        <Link
          to="/"
          className="flex items-center gap-2 px-3 py-2 text-sm bg-surface hover:bg-gray-700 rounded-lg transition-colors"
        >
          <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 19l-7-7m0 0l7-7m-7 7h18" />
          </svg>
          Back to Chat
        </Link>
      </header>

      {/* Main Content */}
      <main className="flex-1 overflow-y-auto">
        <div className="max-w-4xl mx-auto py-8 px-4">
          <h1 className="text-4xl font-bold mb-8 text-center">Legal Information</h1>
          
          {/* Terms of Service */}
          <section className="mb-12">
            <h2 className="text-2xl font-semibold mb-6 text-accent">Terms of Service</h2>
            <div className="bg-surface rounded-lg p-6 space-y-4 text-sm">
              <p className="text-text-secondary">
                <strong>Effective date:</strong> January 1, 2025
              </p>
              
              <div className="space-y-6">
                <div>
                  <h3 className="text-lg font-semibold mb-2">1. Definitions</h3>
                  <p>"Service" means the website, API, applications and all related services operated by GoonGPT.</p>
                  <p>"Content" means any text, audio, images, code or other material that is submitted to or generated by the Service.</p>
                  <p>"User", "you" and "your" mean any person who accesses or uses the Service.</p>
                </div>

                <div>
                  <h3 className="text-lg font-semibold mb-2">2. Eligibility</h3>
                  <p>You must be at least 18 years old to use the Service. By using it, you represent that you meet this requirement and have legal capacity to enter into this agreement.</p>
                </div>

                <div>
                  <h3 className="text-lg font-semibold mb-2">3. License & Ownership</h3>
                  <p><strong>Your input and output.</strong> As between you and us, you own the intellectual‑property rights in both the prompts you supply and the AI‑generated output, subject to any applicable third‑party rights.</p>
                  <p>You grant us a worldwide, non‑exclusive, royalty‑free license to use that Content solely to operate, secure and improve the Service, comply with law, and enforce these Terms.</p>
                </div>

                <div>
                  <h3 className="text-lg font-semibold mb-2">4. Acceptable Use Policy</h3>
                  <p>You agree not to:</p>
                  <ul className="list-disc pl-6 space-y-1">
                    <li>Violate any law or regulation;</li>
                    <li>Infringe, misappropriate or violate anyone's intellectual‑property or privacy rights;</li>
                    <li>Submit or request sexual content involving minors, incitement of violence, instructions for wrongdoing, or other illegal material;</li>
                    <li>Attempt to reverse‑engineer or misuse our models or infrastructure;</li>
                    <li>Use the Service for high‑risk activities where errors could lead to death, personal injury, or severe environmental or financial harm without independent verification.</li>
                  </ul>
                  <p>We may remove Content or suspend accounts that breach this policy.</p>
                </div>

                <div>
                  <h3 className="text-lg font-semibold mb-2">5. AI‑Generated Content Disclaimers</h3>
                  <p>The AI may produce inaccurate, misleading, defamatory, biased or otherwise objectionable output.</p>
                  <p><strong>No professional advice.</strong> Output is provided for general information only and does not constitute legal, financial, medical or professional advice. Always consult a qualified professional.</p>
                  <p>You assume all risk arising from your use of the output.</p>
                </div>

                <div>
                  <h3 className="text-lg font-semibold mb-2">6. Third‑Party Links & Models</h3>
                  <p>The Service may link to or integrate third‑party services. We do not control and are not responsible for third‑party content or practices.</p>
                </div>

                <div>
                  <h3 className="text-lg font-semibold mb-2">7. Disclaimers (Warranties)</h3>
                  <p>The Service and all Content are provided "AS IS" and "AS AVAILABLE." We disclaim all warranties, express or implied, including fitness for a particular purpose, non‑infringement and freedom from malware.</p>
                </div>

                <div>
                  <h3 className="text-lg font-semibold mb-2">8. Limitation of Liability</h3>
                  <p>To the maximum extent permitted by law, our total liability for any claim arising out of or relating to the Service is limited to USD $100. We are not liable for indirect, incidental, consequential or punitive damages, or for lost profits, revenues or data.</p>
                </div>

                <div>
                  <h3 className="text-lg font-semibold mb-2">9. Indemnification</h3>
                  <p>You will indemnify and hold harmless GoonGPT, its affiliates, officers, directors, employees and agents from any claim or demand arising out of your (a) Content, (b) breach of these Terms, or (c) violation of law or third‑party rights.</p>
                </div>

                <div>
                  <h3 className="text-lg font-semibold mb-2">10. DMCA / Copyright Complaints</h3>
                  <p>If you believe Content infringes your copyright, please send a notice to legal@goongpt.com with: (i) identification of the work, (ii) link or reference to the infringing Content, (iii) your contact info, (iv) a statement under penalty of perjury that you own the work, and (v) your signature. We will respond per 17 U.S.C. §512.</p>
                </div>

                <div>
                  <h3 className="text-lg font-semibold mb-2">11. Termination</h3>
                  <p>We may suspend or terminate the Service or your access at any time, with or without notice, for any reason, including violation of these Terms. Upon termination, Sections 5–13 survive.</p>
                </div>

                <div>
                  <h3 className="text-lg font-semibold mb-2">12. Governing Law & Jurisdiction</h3>
                  <p>Unless required by mandatory local law, these Terms are governed by the laws of Delaware, United States, excluding conflict‑of‑law rules. Any dispute will be resolved exclusively in the courts located in Delaware.</p>
                </div>

                <div>
                  <h3 className="text-lg font-semibold mb-2">13. Changes to Terms</h3>
                  <p>We may update these Terms from time to time. We'll post the new version and update the "Effective date." Continued use after the update means acceptance.</p>
                </div>

                <div>
                  <h3 className="text-lg font-semibold mb-2">14. Contact</h3>
                  <p>Questions about these Terms? Email legal@goongpt.com.</p>
                </div>
              </div>
            </div>
          </section>

          {/* Privacy Policy */}
          <section className="mb-12">
            <h2 className="text-2xl font-semibold mb-6 text-accent">Privacy Policy</h2>
            <div className="bg-surface rounded-lg p-6 space-y-4 text-sm">
              <p className="text-text-secondary">
                <strong>Effective date:</strong> January 1, 2025
              </p>
              
              <div className="space-y-6">
                <div>
                  <h3 className="text-lg font-semibold mb-2">1. Who we are</h3>
                  <p>GoonGPT, operated by [Your Company Name], email privacy@goongpt.com ("we", "us", "our").</p>
                </div>

                <div>
                  <h3 className="text-lg font-semibold mb-2">2. What data we collect</h3>
                  <div className="overflow-x-auto">
                    <table className="w-full border-collapse border border-border">
                      <thead>
                        <tr className="bg-gray-700">
                          <th className="border border-border px-3 py-2 text-left">Category</th>
                          <th className="border border-border px-3 py-2 text-left">Examples</th>
                          <th className="border border-border px-3 py-2 text-left">Why we collect</th>
                        </tr>
                      </thead>
                      <tbody>
                        <tr>
                          <td className="border border-border px-3 py-2">Account data</td>
                          <td className="border border-border px-3 py-2">Wallet address, username, profile info</td>
                          <td className="border border-border px-3 py-2">Create and secure your account</td>
                        </tr>
                        <tr>
                          <td className="border border-border px-3 py-2">Usage data</td>
                          <td className="border border-border px-3 py-2">IP address, device type, browser, timestamps, request logs</td>
                          <td className="border border-border px-3 py-2">Operate, debug, prevent abuse, analytics</td>
                        </tr>
                        <tr>
                          <td className="border border-border px-3 py-2">Content data</td>
                          <td className="border border-border px-3 py-2">Prompts you send, AI output you receive</td>
                          <td className="border border-border px-3 py-2">Provide and improve the Service, content safety</td>
                        </tr>
                        <tr>
                          <td className="border border-border px-3 py-2">Cookies & similar tech</td>
                          <td className="border border-border px-3 py-2">Session ID, preference cookies</td>
                          <td className="border border-border px-3 py-2">Keep you logged in, remember settings</td>
                        </tr>
                      </tbody>
                    </table>
                  </div>
                </div>

                <div>
                  <h3 className="text-lg font-semibold mb-2">3. Legal bases (GDPR)</h3>
                  <div className="overflow-x-auto">
                    <table className="w-full border-collapse border border-border">
                      <thead>
                        <tr className="bg-gray-700">
                          <th className="border border-border px-3 py-2 text-left">Basis</th>
                          <th className="border border-border px-3 py-2 text-left">Typical purpose</th>
                        </tr>
                      </thead>
                      <tbody>
                        <tr>
                          <td className="border border-border px-3 py-2">Contract</td>
                          <td className="border border-border px-3 py-2">Provide the Service you requested</td>
                        </tr>
                        <tr>
                          <td className="border border-border px-3 py-2">Legitimate interests</td>
                          <td className="border border-border px-3 py-2">Prevent fraud, ensure network security, improve the model</td>
                        </tr>
                        <tr>
                          <td className="border border-border px-3 py-2">Consent</td>
                          <td className="border border-border px-3 py-2">Non‑essential cookies, marketing emails</td>
                        </tr>
                        <tr>
                          <td className="border border-border px-3 py-2">Legal obligation</td>
                          <td className="border border-border px-3 py-2">Comply with court orders, tax & accounting</td>
                        </tr>
                      </tbody>
                    </table>
                  </div>
                </div>

                <div>
                  <h3 className="text-lg font-semibold mb-2">4. How we use your data</h3>
                  <ul className="list-disc pl-6 space-y-1">
                    <li>Deliver and maintain the Service</li>
                    <li>Monitor, debug and enhance performance</li>
                    <li>Detect, prevent and respond to security incidents and abuse</li>
                    <li>Conduct analytics and research (aggregated/anonymized where possible)</li>
                    <li>Comply with legal requests</li>
                  </ul>
                </div>

                <div>
                  <h3 className="text-lg font-semibold mb-2">5. Sharing of data</h3>
                  <p>We share data only with:</p>
                  <ul className="list-disc pl-6 space-y-1">
                    <li>Cloud hosting, analytics and other vendors who process data for us under contract (confidentiality + security required);</li>
                    <li>Law‑enforcement or courts when legally compelled;</li>
                    <li>Buyers / successors in the event of a merger, acquisition or asset sale (with notice to you).</li>
                  </ul>
                </div>

                <div>
                  <h3 className="text-lg font-semibold mb-2">6. International transfers</h3>
                  <p>If we transfer data outside your jurisdiction, we rely on adequacy decisions, Standard Contractual Clauses, or other lawful mechanisms.</p>
                </div>

                <div>
                  <h3 className="text-lg font-semibold mb-2">7. Security</h3>
                  <p>We use industry‑standard technical and organizational measures (encryption in transit, least‑privilege access, regular audits). No method is 100% secure.</p>
                </div>

                <div>
                  <h3 className="text-lg font-semibold mb-2">8. Retention</h3>
                  <p>We keep personal data only as long as necessary for the purposes above or as required by law, then delete or anonymize it. Conversation logs are typically retained for 30 days unless flagged for abuse or required for legal reasons.</p>
                </div>

                <div>
                  <h3 className="text-lg font-semibold mb-2">9. Your rights</h3>
                  <p>Depending on your jurisdiction, you may have the right to:</p>
                  <ul className="list-disc pl-6 space-y-1">
                    <li>Access and receive a copy of your data;</li>
                    <li>Correct inaccurate data;</li>
                    <li>Delete your data ("right to be forgotten");</li>
                    <li>Object to or restrict processing;</li>
                    <li>Data portability;</li>
                    <li>Withdraw consent.</li>
                  </ul>
                  <p>To exercise these rights, email privacy@goongpt.com.</p>
                </div>

                <div>
                  <h3 className="text-lg font-semibold mb-2">10. Children's privacy</h3>
                  <p>We do not knowingly collect data from children under 18. If you believe we have, contact us to delete it.</p>
                </div>

                <div>
                  <h3 className="text-lg font-semibold mb-2">11. Changes to this Policy</h3>
                  <p>We'll post any changes on this page and, if material, we'll email you or display a prominent notice.</p>
                </div>

                <div>
                  <h3 className="text-lg font-semibold mb-2">12. Contact</h3>
                  <p>For privacy questions or complaints, email privacy@goongpt.com. If unresolved, you may lodge a complaint with your local data‑protection authority.</p>
                </div>
              </div>
            </div>
          </section>

          {/* Content Disclaimer */}
          <section className="mb-12">
            <h2 className="text-2xl font-semibold mb-6 text-accent">Content Disclaimer</h2>
            <div className="bg-surface rounded-lg p-6 space-y-4 text-sm">
              <div className="bg-yellow-900/20 border border-yellow-600/50 rounded-lg p-4">
                <h3 className="text-lg font-semibold mb-2 text-yellow-400">⚠️ Important Notice</h3>
                <p className="text-yellow-200">Content generated by GoonGPT may be offensive, inaccurate, or inappropriate. This service is designed to be uncensored and unfiltered.</p>
              </div>
              
              <div className="space-y-4">
                <div>
                  <h4 className="font-semibold mb-2">Content may include:</h4>
                  <ul className="list-disc pl-6 space-y-1">
                    <li>Mature, adult, or explicit content</li>
                    <li>Controversial or offensive opinions</li>
                    <li>Misinformation or factual errors</li>
                    <li>Biased or discriminatory language</li>
                    <li>Harmful or dangerous suggestions</li>
                  </ul>
                </div>

                <div>
                  <h4 className="font-semibold mb-2">User Responsibility:</h4>
                  <ul className="list-disc pl-6 space-y-1">
                    <li>Verify information from external sources</li>
                    <li>Use critical thinking when evaluating responses</li>
                    <li>Do not follow harmful or dangerous advice</li>
                    <li>Respect others when sharing generated content</li>
                    <li>Comply with applicable laws and regulations</li>
                  </ul>
                </div>

                <div>
                  <h4 className="font-semibold mb-2">By using this service, you acknowledge:</h4>
                  <ul className="list-disc pl-6 space-y-1">
                    <li>You are 18 years or older</li>
                    <li>You understand the uncensored nature of the service</li>
                    <li>You will not hold GoonGPT liable for generated content</li>
                    <li>You will use the service responsibly and ethically</li>
                  </ul>
                </div>
              </div>
            </div>
          </section>
        </div>
      </main>
    </div>
  );
}